[plotly-base-artifacts]
git-tree-sha1 = "6911b15701b79c579653c4e55b24a659e5220efe"

    [[plotly-base-artifacts.download]]
    sha256 = "2b3649d13bb3af0188b1b0de202e2f448e1e4aa4f21de726215e95fc44ad5abc"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/plotly-base-artifacts-2.35.3/plotly-base-artifacts-2.35.3.tar.gz"
