[plotly-base-artifacts]
git-tree-sha1 = "7d71c51782253b7f5736832134a08ca2bdb9a092"

    [[plotly-base-artifacts.download]]
    sha256 = "2cff138b6e71ed250a1d7aa4149ac6014430e23d7dad409e6b3cae58150ffff5"
    url = "https://github.com/sglyon/PlotlyBase.jl/releases/download/plotly-base-artifacts-4.1.1/plotly-base-artifacts-4.1.1.tar.gz"
